import torch
import matplotlib.pyplot as plt

def calculate_sparsity(gates: list[torch.Tensor], threshold: float = 1e-2) -> float:
    """
    Calculates the sparsity across the collected gate tensors.
    Mathematical Intent: A connection is considered "pruned" if its gate survival 
    probability drops below the threshold (e.g. 1e-2). Sparsity is the percentage 
    of such pruned connections over the total parametric shape.
    """
    total_elements = 0
    pruned_elements = 0
    
    for g in gates:
        total_elements += g.numel()
        # Sum the boolean tensor indicating which gates are deeply negative
        pruned_elements += (g < threshold).sum().item()
        
    return (pruned_elements / total_elements) * 100.0 if total_elements > 0 else 0.0

def plot_gate_distribution(gates: list[torch.Tensor], save_path: str = "gate_distribution.png"):
    """
    Generates a matplotlib histogram showing the exact distribution of surviving vs pruned gates.
    Displays the polarization generated by the L1 target exactly as requested.
    """
    all_gate_values = []
    for g in gates:
        # Move back to CPU to interface with Matplotlib easily
        all_gate_values.extend(g.detach().cpu().view(-1).numpy())
        
    plt.figure(figsize=(10, 6))
    plt.hist(all_gate_values, bins=50, alpha=0.75, color='#4A90E2', edgecolor='black')
    plt.title('Self-Pruned Architecture: Gate Probability Distribution', fontsize=14)
    plt.xlabel('Gate Activation Value (0.0 = Pruned, 1.0 = Strong Connection)', fontsize=12)
    plt.ylabel('Frequency (Number of Neuronal Connections)', fontsize=12)
    plt.grid(axis='y', alpha=0.3)
    
    # Save the chart for the report manually as required by JD
    plt.savefig(save_path, dpi=300, bbox_inches='tight')
    plt.close()
